name: Will Runs On Developer push

# on:
#   push:
#     branches:
#       - dev/*
#   pull_request:
#     branches:
#       - dev/*

jobs:
  unit-tests:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install Dependencies
        run: |
          yarn install
      - name: Run Unit tests
        run: |
          yarn run build

